version: '3.6'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build: ./app
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      - mongo
    ports:
      - 4567:4567    
    environment:
      MONGO_HOST: mongo:27017
      MONGO_USER: root
      MONGO_PASSWORD: example
